name 'openstack-storyboard'
version '0.0.1'
source 'git://git.openstack.org/openstack-infra/puppet-storyboard.git'
author 'openstackci'
license 'Apache 2.0'
summary 'Puppet module for the OpenStack StoryBoard'
description 'This module configures StoryBoard either as a standalone, localhost instance or as a fully configurable WSGI app.'
project_page 'https://git.openstack.org/cgit/openstack-infra/puppet-storyboard'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '= 3.2.0'
dependency 'puppetlabs/mysql', '= 0.6.1'
dependency 'puppetlabs/apache', '= 0.0.4'
dependency 'puppetlabs/rabbitmq', '= 5.0.0'
dependency 'example42/puppi', '= 2.1.9'
dependency 'openstackinfra/vcsrepo', '= 0.0.8'
dependency 'stankevich/python', '= 1.6.6'
